### ISSUE TITLE
ios build error

### ISSUE THREAD

**Issue by lijun190422** [scottcgi/Mojoc#10]
error: Build input file cannot be found: '/Users/macbook/Library/Developer/Xcode/DerivedData/SuperLittleRed-bbblipyxsferslfqwskfwtrgnmum/Build/Products/Debug-iphoneos/SuperLittleRed.app/SuperLittleRed'

**Comment by lijun190422** [comment]
not happen after clear project

**Comment by scottcgi** [comment]
OK, if you have any bug or problem please let me know.
