### ISSUE TITLE
Wiki Improvements

### ISSUE THREAD

**Issue by ranjian0** [scottcgi/Mojoc#13]
It is not possible to submit pull requests for the wiki so I am creating this issue to submit some changes (mostly grammar improvements). 
Github also doesn't allow files here, so I have made a zip file with the diff.

[wiki_changes.diff.zip](https://github.com/scottcgi/Mojoc/files/5989586/wiki_changes.diff.zip)

Consider moving the wiki documents to the main repo to make submitting changes more easier.

**Comment by ranjian0** [comment]
Thanks for making the changes, I will create more corrections later in the week. I guess you can close this now.
BTW I love the project, already making an Android Game with the library.

**Comment by scottcgi** [comment]
Thanks for improve wiki and submit issues, and I think you are right. 
So I'm moving wiki to repo and updating some changes.
I will commit it and close this issue.

**Comment by scottcgi** [comment]
The wiki has been moved to repo.
The `Building.md` has been moved to docs.
Your `wiki_changes.diff` has been updated to the docs.
Thanks again !
