### ISSUE TITLE
Feature Request: mojoc for Ubuntu or Windows

### ISSUE THREAD

**Issue by maifeeulasad** [scottcgi/Mojoc#16]
How about mojoc for:
 - Ubuntu
 - Windows

In that case, more cross platform games can be made using just C.

**Comment by ranjian0** [comment]
The description for this project: 
```
A cross-platform, open-source, pure C game engine for mobile game. 
```
Keyword being **Mobile** i,e iOS, Android. 

I had the same idea as you but didn't get too far. The workload to support desktop was very large and I was quite unhappy also with the huge number of dependencies I had to add. I feel like the project is much more suited to mobile development. 

Just my opinion.

**Comment by nezvers** [comment]
At least WASM would be a great addition since that could be a workaround for desktop dependency variability.
