### ISSUE TITLE
RE: some questions

### ISSUE THREAD

**Issue by Joe23232** [scottcgi/Mojoc#17]
Hi I have some questions regarding this project:
1. Is there a game editor or something for this game engine?
2. Is there integrated ECS?
3. Does it ONLY support OpenGL?
4. If `3` is applicable, then how does OpenGL performance compare to Vulkin?

**Comment by ranjian0** [comment]
1. No editor
2. Not exactly: https://github.com/scottcgi/Mojoc/blob/master/Docs/ComponentArchitecture.md
3. Yes. OpenGL only.
4. Vulkan is obviously faster but I would imagine it is overkill for this project.

**Comment by Joe23232** [comment]
I see, thanks mate
