### ISSUE TITLE
About the logo.

### ISSUE THREAD

**Issue by finscn** [scottcgi/Mojoc#2]
In the official explain about the logo :

> M : ears  
OO: eyes  
J : body  
C : tail 

But , I asked more than 10 friends , they've given me the same answer : 

![logo](https://user-images.githubusercontent.com/288367/36648434-99b47b7c-1ace-11e8-8209-46372f515b0e.png)

I think  you should think redesign the logo , or change the official explain.

**Comment by scottcgi** [comment]
haha... very interesting, I will think about it, thanks 😉
