### ISSUE TITLE
I'm excited about your publish

### ISSUE THREAD

**Issue by chenfanggm** [scottcgi/Mojoc#3]
Hi Scott,
I'm so excited about your publishing of Mojoc. I'm currently learning how to create a game engine, and appreciate that more Chinese are to start making game engine. Eventually, more and more great games and movies are going to be new born in main land China. I didn't read your code yet, but I will. I may have plenty of questions about why some way is better in which you chose to do. Plz keep improving this project by all good thought and practices.

Thanks,
Chen

**Comment by scottcgi** [comment]
Thanks for your attention, and welcome issues and questions. 😎
