### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [scottcgi/Mojoc#5]
Would you like to add more error handling for return values from functions like the following?
- [fopen](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream") ⇒ [CreateDataFrom](https://github.com/scottcgi/Mojoc/blob/4b5b6d47c4e4efd3477d2d2b53051058f0ee704a/Engine/Toolkit/Utils/FileTool.c#L36)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [Create](https://github.com/scottcgi/Mojoc/blob/4b5b6d47c4e4efd3477d2d2b53051058f0ee704a/Engine/Toolkit/Utils/Array.c#L14)

**Comment by scottcgi** [comment]
I think the fopen can add error code handling, but the malloc I feel not very necessary.
Because the malloc failure is very rare.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by scottcgi** [comment]
Not now, unless there is a related bug.

**Comment by elfring** [comment]
* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by scottcgi** [comment]
I wrote 3 years j2ee that use java with Spring framework, and use AOP to handle exceptions and database transactions.

I felt the power and benefits of AOP, but I think it‘s not suitable for game and game engine, also small software.

Because AOP is too complicated and may have performance issues.

**Comment by elfring** [comment]
>I felt the power and benefits of AOP,

This is nice.


>but I think it‘s not suitable for game and game engine,

I wonder about such a view.


>also small software.

Will your development evolve in ways where source code sizes will be significant?

How many design patterns are you going to apply here?


>Because AOP is too complicated

Aspect-oriented programming triggers specific development challenges.


>and may have performance issues.

Can this concern be adjusted so that further progress could be achieved?
