### ISSUE TITLE
 fatal error: 'Engine/Toolkit/Head/UserData.h' file not found

### ISSUE THREAD

**Issue by heaoven** [scottcgi/Mojoc#7]
when build android project,error occure,follow  tip:
Mojoc/Samples/SuperLittleRed/Code/GameMap.c:12:10: fatal error: 'Engine/Toolkit/Head/UserData.h' file not found
branch:Develop
commit:4c818b4d802ccf3fda125bbc3bf486b3bb36f3f7

**Comment by scottcgi** [comment]
Please don't use **Branch Develop** to build，but use **Branch master**.

Because the current **Branch Develop** has many changes, including files and APIs. I'm working on these changes and haven't fully committed.

So you can open a new issue if  **Branch master** has any errors.
