### ISSUE TITLE
如果不使用NativeActivity该怎么使用这个库？

### ISSUE THREAD

**Issue by wuhuisai** [scottcgi/Mojoc#8]
如果不使用NativeActivity该怎么使用这个库？

**Comment by scottcgi** [comment]
这个 [Application.h](https://github.com/scottcgi/Mojoc/blob/fe8a5b6a0754cbbc1b3f7b2e0daf688ebc439db0/Engine/Application/Application.h) 是整个程序的运行接口，在Java里面回调这里的函数。

可以参考IOS的处理，IOS上就没有NativeActivity，[GameViewController.swift](https://github.com/scottcgi/Mojoc/blob/master/Samples/SuperLittleRed/IOS/GameViewController.swift)，是IOS使用Application.h的方法。

**Comment by wuhuisai** [comment]
好的，谢谢
